# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=b'images/default.jpeg', upload_to=b''),
        ),
    ]
